### ISSUE TITLE
where to  download large model?

### ISSUE THREAD

**Issue by luoolu** [cfeng783/GTT#1]
please give download link

**Comment by IkeYang** [comment]
+1

**Comment by cfeng783** [comment]
Dear both, thanks for your interest in our work. We decided not to open source the largest model due to several restrictions at this moment. Will let you know when we are able to open source the largest model.

**Comment by rainbownmm** [comment]
+1

**Comment by cfeng783** [comment]
The large model checkpoint is available at https://drive.google.com/file/d/1wLgOKEeezRgq_ThF3TcVl7KiJW6duAmS/view?usp=sharing
