### ISSUE TITLE
The model after fine-tuning uses zeroshot_api to report an error

### ISSUE THREAD

**Issue by rainbownmm** [cfeng783/GTT#2]
Thanks for your work, I have some doubts, the small version of the model without fine-tuning performed very poorly on my dataset, so I tried to change the model with fine-tuning, first I tried fine-tuning on the official electricity dataset, fine-tuning After success, I encountered the following error when using it. 

{'ret': 'fail', 'message': 'all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 720 and the array at index 1 has size 64'}

I would be grateful if you could provide an API for the fine-tuned model.

**Comment by rainbownmm** [comment]
Still not solved. Does this have something to do with the length 720 I chose when fine-tuning?

**Comment by rainbownmm** [comment]
I noticed that this code loads the model
def load_pretrained(self, modelpath):



         self.configs = pickle.load(open(os.path.join(modelpath,'configs.pkl'),'rb'))
         print(self.configs)
         self.configs = ModelConfig(**self.configs)
         pm = TSFoundation.load_model(model_path=modelpath)
        
         self.configs.target_dim = len(self.targets+self.covariates)
         self.configs.covariate_dim = 0
         self.configs.timefeat_dim = len(self.timefeats)


         self.configs.enable_revin = True

         self.configs.affine = False
         self.configs.revin_time = True
         print(self.configs)
         print('end...')
         self.estimator = GTTNet.from_pretrained(pm,self.configs)

        
         # self.configs['target_dim'] = 10
        
         self.estimator.compile(optimizer='adam', loss='mae', run_eagerly=True)
         return self

**Comment by rainbownmm** [comment]
There is a difference between the model before fine-tuning and after fine-tuning
small model: ModelConfig(block_size=1024, patch_size=64, target_dim=12, covariate_dim=0, timefeat_dim=6, embedd_pdrop=0.0, dropout=0.0, activation_dropout=0.0, attention_dropout=0.0, n_embd=512, encoder_layers=6, encoder_attention_heads =8, encoder_layerdrop=0.0, encoder_ffn_dim=2048, enable_revin=True, affine=False, revin_time=True, forecast_mode='point', pred_len=None)

After fine-tuning: ModelConfig(block_size=1024, patch_size=64, target_dim=12, covariate_dim=0, timefeat_dim=6, embedd_pdrop=0.0, dropout=0.0, activation_dropout=0.0, attention_dropout=0.0, n_embd=512, encoder_layers=6, encoder_attention_heads =8, encoder_layerdrop=0.0, encoder_ffn_dim=2048, enable_revin=True, affine=False, revin_time=True, forecast_mode='point', pred_len=720)

**Comment by rainbownmm** [comment]
I have made certain restrictions on the value of x_next. The code is running temporarily, but the effect does not seem to be as good as the small model. I wonder if you can provide a complete fine-tuning example, including using gttapi to call model prediction. Thank you very much.

**Comment by cfeng783** [comment]
Thanks for your interest in work, we will provide a complete version in the future. Will notice you once available.
